### ISSUE TITLE
Phrasing of "Let's accept that" can mislead...

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-1-mapping-arrays-readme#4]
### Canvas Link

https://learning.flatironschool.com/courses/5185/pages/mapping-arrays?module_item_id=396141

### Concern

Technically, this phrase makes grammatical sense:
Let's accept that callback function as the second argument to map():

However, as a reader, my initial reading of those first three words was as:
Let's accept that the sky is blue.

Given this orientation, I had to backup, reread, reconsider, reprocess - all of that, in order to make sense of the sentence.
That's not useful work/mental processing. Can this line be simplified?

### Suggested Changes

Instead of:
Let's accept that callback function as the second argument to map():

How about:
So, let's use that callback function as the second argument to map():

or:
So, let's take that callback function as the second argument to map():

**Comment by lizbur10** [comment]
Hi @brigj1 ! When you have multiple comments on the same lesson or lab, could you please submit them all in a single issue? That would really help us out.

Thanks! 💙
